// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

int i = 0;
int sumEven = 2;

int num1 = 1;
int num2 = 2;

while (i <= 4000000)
{
    i = num1 + num2;

    num1 = num2;
    num2 = i;

    if (i % 2 == 0 && i <= 4000000)
    {
        sumEven += i;
        // Console.WriteLine(sumEven);
    }

}

Console.WriteLine("The sum of all even numbers is {0}", sumEven);